version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
      - npm install -g @angular/cli@9.0.6

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ng build --prod

  #post_build:
   # commands:
      #- aws s3 cp dist/my-angular-project s3://b10-code-pipeline-website-bucket1 --recursive
      

artifacts:
  files:
    - "dist/my-angular-project/**/*"  # Include the built Angular app
    - "appspec.yml"                   # Include the appspec.yml file for CodeDeploy
